### ISSUE TITLE
Unable to boot app in Intellij due to environment variables

### ISSUE THREAD

**Issue by eddiezane** [TwilioDevEd/automated-survey-spring#1]
I'm unable to boot the app in Intellij because I can't seem to get the environment variables to load inside gradle tasks.

I was able to get it running manually, but Java developers use IDE's.

We should consider some sort of config file that gets slurped up into the environment like [dotenv](https://github.com/bkeepers/dotenv).

**Comment by jarodreyes** [comment]
+1 @jsantos17

**Comment by kwhinnery** [comment]
This is probably a README documentation fix. [IntelliJ supports project-specific environment variables](https://www.jetbrains.com/idea/help/path-variables-2.html), as does [Eclipse](http://help.eclipse.org/mars/index.jsp?topic=%2Forg.eclipse.jdt.doc.user%2Ftasks%2Ftasks-java-local-configuration.htm). Think we can continue a code review if it's runnable from the command line, but update the README with Eclipse/IntelliJ setup instructions.

**Comment by eddiezane** [comment]
If anyone can get those to carry through to the gradle tasks I'd love to know the secret.

You're also unable to define run configuration environment variables for a gradle build for some reason.

**Comment by mcelicalderon** [comment]
I was able to make the application work on IntelliJ just by changing one of the gradle dependencies

```
//Instead of making it available only in runtime
compile("org.springframework.boot:spring-boot-starter-tomcat")
```

Now after you import the app as a gradle project you should just configure the IDE to run the main class `SurveyJavaApplication` and set the environment variables there. I'll edit the readme file to make it as clear as posible how to run the project with intellij, even with some screenshots.

**Comment by eddiezane** [comment]
Thanks @mcelicalderon! Instructions are super clear now.
